Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information
AllowedHosts: '*'
AddAdministration:
  Path: /administration
  IdentityServer:
    Authority: 'http://127.0.0.1:5100'
    ApiName: ocelot
    ApiSecret: secret
    RequireHttpsMetadata: false