Routes: 
-   UpstreamPathTemplate: '/{url}'
    DownstreamScheme: http
    DownstreamPathTemplate: '/{url}'
    DownstreamHostAndPorts:
      - Host: 127.0.0.1
        Port: 5003
    UpstreamHttpMethod: ["Get", "Post", "Put"]
    UpstreamPathTemplalte: '/protect/{url}'
    AuthenticationOptions: 
     - AuthenticationProviderKey: 'ocelot'
       AllowedScopes: []
    RouteClaimsRequirement: {}
GlobalConfiguration:
  BaseUrl: 'http://127.0.0.1:5000'